name: Build WildFly Common

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Check out project
      uses: actions/checkout@v4
      with:
        path: wildfly-common

    - name: Set up JDKs
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        cache: maven
        java-version: |
          17
          21
          23

    - name: Build & Test with Maven
      run: |
        cd wildfly-common
        mvn -B -ntp -N install --file pom.xml -Djava17.home="${{env.JAVA_HOME_17_X64}}" -Djava21.home="${{env.JAVA_HOME_21_X64}}"
