name: Build WildFly Common

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '17']
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    - name: Build & Test with Maven on JDK ${{ matrix.java }}
      run: mvn -B package --file pom.xml
    - name: Test with Maven on JDK 8
      run: mvn -B test --file pom.xml -Djava8.home="$JAVA_HOME_8_X64"
